config/routes.rb
Rails.application.routes.draw do
  get 'items/create'

    resources :lists do
      resources :items
    end

  root "lists#index"

  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }

  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  get '/auth/:provider/callback', to: 'sessions#create'





end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/identity.rb
class Identity < ApplicationRecord
  belongs_to :user
  validates_presence_of :uid, :provider
 validates_uniqueness_of :uid, :scope => :provider

 def self.find_for_oauth(auth)
   find_or_create_by(uid: auth.uid, provider: auth.provider)
 end
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :list # Add methods to my model.
  validates :description, :presence => true
  STATUS = {
    :incomplete => 0,
    :complete => 1
  }

  def complete?
    self.status == STATUS[:complete]
  end

  def incomplete?
    self.status == STATUS[:incomplete]
  end
end

app/models/list.rb
class List < ApplicationRecord
  has_many :items
  has_many :shared_lists
  has_many :users, :through => :shared_lists
  belongs_to :user
  has_many :members, through: :list_members


  validates :name, :presence => true


  accepts_nested_attributes_for :items
end

app/models/list_member.rb
class ListMember < ApplicationRecord
  belongs_to :list
  belongs_to :member, class_name: "User"
end

app/models/shared_list.rb
class SharedList < ApplicationRecord

  belongs_to :list
  belongs_to :user


end

app/models/squad.rb
class Squad < ApplicationRecord
  has_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :squad
  has_many :shared_lists
  has_many :lists, :through => :shared_lists
  has_many :list_members, foreign_key: 'member_id'

  TEMP_EMAIL_PREFIX = 'change@me'
  TEMP_EMAIL_REGEX = /\Achange@me/

  # Include default devise modules. Others available are:
  # :lockable, :timeoutable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]

  validates_format_of :email, :without => TEMP_EMAIL_REGEX, on: :update


  def self.find_for_oauth(auth, signed_in_resource = nil)

    # Get the identity and user if they exist
    identity = Identity.find_for_oauth(auth)

    # If a signed_in_resource is provided it always overrides the existing user
    # to prevent the identity being locked with accidentally created accounts.
    # Note that this may leave zombie accounts (with no associated identity) which
    # can be cleaned up at a later date.
    user = signed_in_resource ? signed_in_resource : identity.user

    # Create the user if needed
    if user.nil?

      # Get the existing user by email if the provider gives us a verified email.
      # If no verified email was provided we assign a temporary email and ask the
      # user to verify it on the next step via UsersController.finish_signup
      email_is_verified = auth.info.email && (auth.info.verified || auth.info.verified_email)
      email = auth.info.email if email_is_verified
      user = User.where(:email => email).first if email

      # Create the user if it's a new registration
      if user.nil?
        user = User.new(
          name: auth.extra.raw_info.name,
          #username: auth.info.nickname || auth.uid,
          email: email ? email : "#{TEMP_EMAIL_PREFIX}-#{auth.uid}-#{auth.provider}.com",
          password: Devise.friendly_token[0,20]
        )

        user.save!
      end
    end

    # Associate the identity with the user if needed
    if identity.user != user
      identity.user = user
      identity.save!
    end
    user
  end

  def email_verified?
    self.email && self.email !~ TEMP_EMAIL_REGEX
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
   before_action :authenticate_user!, except: [:create, :new]

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  # before_action :set_item, only: [:show, :edit, :update, :destroy]

  def index
    @items = Item.all
  end


  def show
  end

  def new
    @item = Item.new
  end


  def edit
  end


  def create
    @list = List.find(params[:list_id])
    @item = @list.items.build(item_params)
    if @item.save
      redirect_to list_path(@list)
    else
      render "lists/show"
    end
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)

    redirect_to list_path(@item.list)
  end


  def destroy
    @item.destroy
    redirect_to items_url, notice: 'Item was successfully destroyed.'

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:description, :status, :list_id)
    end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  # before_action :set_list, only: [:show, :edit, :update, :destroy]

  # GET /lists
  # GET /lists.json
  def index
    @lists = List.all
    @list = List.new
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
    @list = List.find(params[:id])
    @item = Item.new
  end

  # GET /lists/new
  def new
    @list = List.new
    # @list.items.build
  end


  def edit
    @list = List.find(params[:id])
  end


  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_url(@list)
    else
      @lists = List.all
      render :index
    end
  end


  def destroy
    @list.destroy
    redirect_to lists_url, notice: 'List was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:name, :items_attributes => [:description])
    end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def self.provides_callback_for(provider)
    class_eval %Q{
      def #{provider}
        @user = User.find_for_oauth(env["omniauth.auth"], current_user)

        if @user.persisted?
          sign_in_and_redirect @user, event: :authentication
          set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
        else
          session["devise.#{provider}_data"] = env["omniauth.auth"]
          redirect_to new_user_registration_url
        end
      end
    }
  end
  #removed twitter, google etc
  [:facebook].each do |provider|
    provides_callback_for provider
  end

  def after_sign_in_path_for(resource)
    if resource.email_verified?
      super resource
    else
      finish_signup_path(resource)
    end
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
  def li_class_for_item(item)
    "completed" if item.complete?
  end

  def li_for_item(item)
    content_tag_for :li, item, :class => li_class_for_item(item) do
      yield
    end
  end

  def form_for_item_status(item)
    form_for([item.list, item]) do |f|
      f.check_box :status, :class => "toggle", :checked => item.complete?
    end
  end

end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/items/_form.html.erb
<%= form_for(item) do |f| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :status %>
    <%= f.check_box :status %>
  </div>

  <div class="field">
    <%= f.label :list_id %>
    <%= f.number_field :list_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/_item_li.html.erb
<%= li_for_item(item) do %>
  <div class="view">
    <%= form_for_item_status(item) %>

    <label><%= item.description %></label>
  </div>
<% end %>

app/views/items/create.html.erb
<h1>Items#create</h1>
<p>Find me in app/views/items/create.html.erb</p>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Items</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Status</th>
      <th>List</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.description %></td>
        <td><%= item.status %></td>
        <td><%= item.list_id %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>

<p>
  <strong>Status:</strong>
  <%= @item.status %>
</p>

<p>
  <strong>List:</strong>
  <%= @item.list_id %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GroceryGetters</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>

  <footer>
    
    <%= link_to 'Sign Out', destroy_user_session_path, method: :delete%>
  </footer>
</html>

app/views/lists/_form.html.erb
<%= form_for(@list) do |list_form| %>
  <p><%= list_form.label :name %> <%= list_form.text_field :name %></p>

  <p>
    <%= list_form.fields_for :items, @list.items do |item_field| %>
      <p>
        <%= item_field.text_field :description %>
      </p>
    <% end %>
  </p>


  <%= list_form.submit %>
<% end %>

app/views/lists/edit.html.erb
<h1>Edit List: <%= @list.name %></h1>

<%= render 'form' %>

<%= link_to 'Show', @list %> |
<%= link_to 'Back', lists_path %>

app/views/lists/index.html.erb
<section class="todoapp">
  <header class="header">
    <h1>Your Lists</h1>
    <%= form_for(@list) do |f| %>
      <%= f.text_field :name, :class => "new-todo", :placeholder => (@list.errors.full_messages_for(:name).first || "Enter a new list name...") %>
      <%= f.submit :style => "display: none" %>
    <% end %>
</form>
  </header>
  <section class="main">
    <input class="toggle-all" type="checkbox">
    <label for="toggle-all">Mark all as complete</label>
    <ul class="todo-list">
      <% @lists.each do |list| %>
      <li>
        <div class="view">
          <label><%= link_to list.name, list_path(list) %></label>
        </div>
      </li>
      <% end %>
    </ul>
  </section>
  <footer class="footer">
  </footer>
</section>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<section class="todoapp">
  <header class="header">
    <h1><%= @list.name %></h1>
    <%= form_for([@list, @item]) do |f| %>
      <%= f.text_field :description, :class => "new-todo", :placeholder => (@item.errors.full_messages_for(:description).first || "Enter a new item...") %>
      <%= f.submit :style => "display: none" %>
    <% end %>
  </header>
  <section class="main">
    <input class="toggle-all" type="checkbox">
    <label for="toggle-all">Mark all as complete</label>
    <ul class="todo-list">
      <%= render :collection => @list.items, :partial => "items/item_li", :as => :item %>
    </ul>
  </section>
  <footer class="footer">
    <div>Add Users to List
      

    </div>

  </footer>
</section>